config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'admin/posts'
root 'home#index'
 namespace :admin do
 root 'home#index' 
 resources :posts
 resources :users  
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  STATUSES = {
    admin: 'admin',
    user: 'user',
    editor: 'editor'
  }

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :user_status
  def index
  end

  private
  def user_status
    if current_user.status == 'user'
      redirect_to root_path
      else
        return true
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :authenticate_user!
	def index
		@posts = Post.page(params[:page])
	end
	def new
		@post = Post.new
	end
	def edit
		@post = Post.find(params[:id])
	end
	def create
		user = current_user
		@post = user.posts.create(post_params)
		if @post.save
			flash[:success] = t('admin.posts.create')
			redirect_to admin_post_path(@post)
		else
			flash[:danger] = t('admin.posts.error')
			redirect_to new_admin_post_path
		end
	end
	def update
		@post = Post.find(params[:id])
		@post.update(post_params)
		redirect_to admin_post_path(@post)
	end
	def show 
		@post = Post.find(params[:id])
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to admin_posts_path
	end
	private
	def post_params
		params.require(:post).permit(:title, :content, :photo)
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: %i[show edit update destroy]
  before_action :user_status
  def index
    @users = User.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = t('admin.users.update')
      redirect_to admin_user_path(@user)
    else
      flash[:danger] = t('admin.users.errors.error')
      render 'edit'
    end
  end

  private
    def user_status
        if current_user.status == 'admin'
      return true
    else
        redirect_to admin_root_path
   end
  end
  
  def find_user
    @user = User.find_by_id(params[:id])
    return if @user

    flash[:danger] = t('admin.users.errors.not_found')
    redirect_to admin_root_path
  end

  def user_params
    params.require(:user).permit(:status)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<h1>Admin::Home#index</h1>
<p>Find me in app/views/admin/home/index.html.erb</p>

app/views/admin/posts.html.erb
<h1>Admin#posts</h1>
<p>Find me in app/views/admin/posts.html.erb</p>

app/views/admin/posts/_form.html.erb
<div class="row">
	<div class="col-md-8 mx-auto">
		<%= form_for [:admin, @post] do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :content %>
			<%= f.text_field :content, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :photo %>
			<%= f.file_field :photo, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit class: 'btn btn-success form-control' %>
		</div>
		<% end %>
	</div>
</div>

app/views/admin/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h2 class="text-center">Edit Post</h2>
		</div>
	</div>
	<%= render 'form' %>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			
			<table class="table table-bordered">
				<tr>
					<th>Title</th>
					<th>Content</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
				<% @posts.each do |post| %>
				<tr>
					<td>
						<%= link_to post.title, admin_post_path(post) %>
					</td>
					<td>
						<%= post.content %>
					</td>
					<td>
						<%= link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-info' %>
					</td>
					<td>
						<%= button_to 'Delete', [:admin, post], method: :delete, class: 'btn btn-danger' %>
					</td>
				</tr>
				<% end %>
			</table>
			<%= paginate @posts %>
		</div>
	</div>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h2 class="text-center">New Post</h2>
		</div>
	</div>
	<%= render 'form' %>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h1><%= @post.title %></h1>
		</div>
	</div>
	<div class="row">
		
		<div class="col-md-6">
			<p>
				<%= @post.content %>
			</p>
		</div>
		<% if @post.photo.present? %>
		<%= image_tag @post.photo, :size => '1000x1000' %>
		<% else %>
		<img src="/georgi.jpg">
		<% end %>
	</div>
</div>

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", admin_root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", admin_posts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", admin_users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
    <%= link_to 'Main', root_path, class: 'btn btn-primary' %>
    <% if current_user %>
        <%= button_to 'LogOut', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success' %>
        <% else %>
          <%= link_to 'LogIn', new_user_session_path, class: 'btn-outline-success' %>
          <% end %>
  </div>
</nav>

app/views/admin/users/edit.html.erb
<div class="container">
	<div class="row mt-5">
		<div class="col">
			<h1 class="text-center">Edit User Status</h1>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-md-6 mx-auto">
			<%= form_for [:admin, @user] do |f| %>
			<div class="form-group">
				<%= f.select(:status, User::STATUSES , {include_blank: 'Change Status'}, {class: 'form-control'}) %>
			</div>
			<div class="form-group mt-1">
				<%= f.submit class: 'btn btn-primary' %>
			</div>
			<% end %>
		</div>
	</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">
      <h2 class="text-center">All Users</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email Name</th>
            <th>Status</th>
            <th>View</th>
            <th>Edit</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
              <td><%= user.status %></td>
              <td><%= link_to 'Show', admin_user_path(user), class: 'btn btn-info' %></td>
              <td><%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-info' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
	<div class="row mt-5">
		<div class="col">
			<h2 class="text-center">User Information</h2>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% if current_user %>
<p><%= current_user.first_name %></p>
<p><%= current_user.status %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Last1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if controller_path =~/^admin\// %>
      <%= render 'admin/shared/header' %>
    <% else %>
    <%= render 'shared/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <% if current_user &&(current_user.status == 'admin' || current_user.status == 'editor') %>
           <%= link_to 'Admin', admin_root_path, class:'btn btn-outline-success' %>
      <% end %>
      
      <% if current_user %>
        <%= button_to 'LogOut', destroy_user_session_path, method: :delete, class:'btn btn-outline-success' %>
      <% else %>
        <%= link_to 'LogIn', new_user_session_path, class:'btn btn-outline-success' %>
      <% end %>
    </div>
  </div>
</nav>